// <auto-generated />
namespace StudentDormitoryManagementSystem.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Changeitemreserveproperty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changeitemreserveproperty));
        
        string IMigrationMetadata.Id
        {
            get { return "201908281825192_Change-item-reserve-property"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
